services:
  - type: web
    name: line-techorange-newsbot
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel &&
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "False"
      - key: MAX_ARTICLES
        value: "3"
