services:
  - type: web
    name: line-techorange-newsbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "10000"
      - key: HOST
        value: "0.0.0.0"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "False"
      - key: MAX_ARTICLES
        value: "3"
    plan: free
